app: cd ../build && ninja app && ./app
server: sleep 2.5; python -u server.py ../build/app.sock 9999 7000
client: sleep 3.5; python -u client.py ../build/app.sock 9998 localhost:localhost:7000

test1: nc -v -l -p 9999 >/dev/null
